name: Node.js CI

on:
  push:
    branches: [ main, versions/** ]
  pull_request:
    branches: [ main, versions/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 16.x, 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn run lerna bootstrap
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run prettier:check
  docs:
    if: ${{ github.event_name == 'push' }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn
      - run: yarn run lerna bootstrap
      - run: yarn run build
      - env:
          BUILD_NUMBER: ${{ github.run_number }}
          REPO_USER: ${{ github.repository_owner }}
          GIT_REF: ${{ github.ref }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: scripts/github/publishDocs.sh
