name: Node.js CI

on:
  push:
    branches: [ main, versions/** ]
  pull_request:
    branches: [ main, versions/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn
      - run: yarn run lerna bootstrap
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run prettier:check
      - name: Save build assets
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: |
            packages/*/lib
            packages/*/es
            node_modules/.cache/tsukuru
  test:
    strategy:
      matrix:
        node-version: [ 18, 16, 14 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Load build assets
        uses: actions/download-artifact@v3
        with:
          name: build-result
      - run: yarn test
  docs:
    if: ${{ github.event_name == 'push' }}
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Load build assets
        uses: actions/download-artifact@v3
        with:
          name: build-result
      - env:
          BUILD_NUMBER: ${{ github.run_number }}
          REPO_USER: ${{ github.repository_owner }}
          GIT_REF: ${{ github.ref }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: scripts/github/publishDocs.sh
